create table PG560_USER(
	id integer generated by default as identity primary key,
	username varchar(30) not null, 
	password varchar(30) not null
	);

insert into PG560_USER(username, password) values( 'Ola', 'Ola');
insert into PG560_USER(username, password) values( 'Kari', 'Kari');

